# Sidebar navigation

- label: 'About'
  link: '/'
- label: 'Quick Start Guide'
  link: '/quick-start-guide'
  
- label: Curriculum
  items:
    - label: '1: Foundations'
      link: '/usage/curriculum/Section_1'
    - label: '2: Ideating'
      link: '/usage/curriculum/Section_2'
    - label: '2.5: More Ideas'
      link: '/usage/curriculum/Section_2.5'
    - label: '3: Basics of Design'
      link: '/usage/curriculum/Section_3'
    - label: '4: Expanding Designs'
      link: '/usage/curriculum/Section_4'
    - label: '5: Type Families'
      link: '/usage/curriculum/Section_5'
    - label: '6: History'
      link: '/usage/curriculum/Section_6'
- label: More
  items:
    - label: 'About Space Type Co'
      link: https://spacetypecontinuum.com/
    - label: Donate
      link: https://www.paypal.com/donate?hosted_button_id=EJMNLBTAH6WUA